name: CI/CD with Access Keys

on:
  push:
    branches: [ "main" ]
    # paths: [ "src/product-catalog/**" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout Code
        env:
          ACCOUNT_ID: "281934899426"
          IMAGE_TAG: ${{ github.sha }}
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: learning
          IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
        run: |
          cd src/product-catalog
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: sandeep000017/ultimate-devops-project-demo # Replace with your GitOps repo path
          token: ${{ secrets.GITOPS_PAT }}

      - name: Update Image Tag in Manifest
        run: |
          IMAGE="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/learning:${IMAGE_TAG}"
          sed -i "/name: *productcatalogservice/,/image:/s|^\([[:space:]]*image:\).*|\1 ${IMAGE}|" kubernetes/productcatalog/deploy.yaml
          cat kubernetes/productcatalog/deploy.yaml | grep image
    
      - name: Commit and Push to GitOps
        run: |
          git config --global user.email "sandeeptalluri017@gmail.com"
          git config --global user.name "sandeep000017"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CI]: Update catalog to ${{ needs.build-and-push.outputs.image_tag }}"
          git push origin main
